version: '3.8'

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: File Browser
  group: Utils
  description: Manage your local files from the browser
  fields:
    - name: FILEBROWSER_ROOT_PATH
      description: Local path to browse
      default: "/tmp"
    - name: FILEBROWSER_PORT
      advanced: True
      description: Web UI port
      default: 8080
    - name: TZ
      advanced: True
      description: Service time zone
      default: "Europe/London"
  success: Web UI ready on http://[[IP]]:[[FILEBROWSER_PORT]]

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  filebrowser:
    image: filebrowser/filebrowser:s6 
    ports:
      - ${FILEBROWSER_PORT:-8080}:80
    volumes:
      - ${FILEBROWSER_ROOT_PATH:-/tmp}:/srv
      - filebrowser-db:/database
      - filebrowser-config:/config 
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}     

# ---------------------------------------------------------------------------
# PERSISTENT STORAGE
# ---------------------------------------------------------------------------

volumes:
  filebrowser-db:
  filebrowser-config: