version: '3.7'

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: Node-RED
  group: Utils
  description: No-code flow management UI
  fields:
    - name: PORT
      description: Port the service will be listening on
      default: 1880
  success: You can now visit the Node-RED web UI at http://[[IP]]:[[PORT]]

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  nodered:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    user: node-red
    restart: unless-stopped
    privileged: true
    volumes:
      - 'node-red-data:/data'
    ports:
      - ${PORT:-1880}:1880
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS:-false}

# ---------------------------------------------------------------------------
# PERSISTENT VOLUMES
# ---------------------------------------------------------------------------

volumes:
  node-red-data:

