version: '3.8'

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: Zigbee2MQTT
  group: Zigbee
  description: Support for Zigbee devices
  fields:
    - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
      description: Mount point for the Zigbee concentrator
      default: "/dev/ttyUSB0"
    - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
      description: Address of the MQTT broker to publish to
      default: "mqtt://{{IP}}:1880"
    - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
      advanced: True
      description: Port for the web interface
      default: "zigbee2mqtt"
    - name: ZIGBEE2MQTT_CONFIG_PORT
      advanced: True
      description: Port for the web interface
      default: 8080
  success: You can now visit the Zigbee2MQTT web UI at http://{{IP}}:{{ZIGBEE2MQTT_CONFIG_PORT}}

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:
  
  zigbee2mqtt:
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee2mqtt-data:/app/data
    ports:
      - ${ZIGBEE2MQTT_CONFIG_PORT:-8080}:8080
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=${ZIGBEE2MQTT_CONFIG_PERMIT_JOIN:-true}
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=${ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC:-zigbee2mqtt}
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=${ZIGBEE2MQTT_CONFIG_MQTT_SERVER:-mqtt://mqtt}
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=${ZIGBEE2MQTT_CONFIG_SERIAL_PORT:-/dev/ttyUSB0}
      - ZIGBEE2MQTT_CONFIG_FRONTEND=${ZIGBEE2MQTT_CONFIG_FRONTEND:-true}
    devices:
      - ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT:-/dev/ttyUSB0}:${ZIGBEE2MQTT_CONFIG_SERIAL_PORT:-/dev/ttyUSB0}

# ---------------------------------------------------------------------------
# PERSISTENT STORAGE
# ---------------------------------------------------------------------------

volumes:
  zigbee2mqtt-data: