version: '3.4'

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: BasicStation
  group: LoRaWAN
  description: BasicStation Packet Forwarder for LoRaWAN Gateways
  fields:
    - name: MODEL
      description: Concentrator model
      default: "RAK5146"
      options: ["RAK5146","RAK2287","RAK2245","RAK2246","RAK2247","RAK831","RAK833","RAK7243","RAK7243C","RAK7244","RAK7244C","RAK7246","RAK7246G","RAK7248","RAK7248C","RAK7271","RAK7371","IC880A","WM1302","R11E-LR8","R11E-LR9","SX1301","SX1302","SX1303","SX1308"]
    - name: INTERFACE
      advanced: True
      description: Concentrator interface
      default: "AUTO"
      options: ["AUTO","SPI","USB"]
    - name: DEVICE
      advanced: True
      description: Device mount point for the concentrator (i.e. "/dev/spidev0.0")
      default: "/dev/spidev0.0"
    - name: GW_RESET_GPIO
      advanced: True
      description: GPIO to reset the concentrator (only for SPI concentrators)
      default: 17
    - name: TTS_REGION
      advanced: True
      description: Region of the TTN cluster
      default: "eu1"
      options: ["eu1", "nam1", "au1"]
    - name: TC_URI
      advanced: True
      description: Address of the LNS server (leave empty to use TTS cluster based on TTS_REGION above, must begin with "wss://")

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: "${MODEL:-RAK5146}"
      INTERFACE: "${INTERFACE:-AUTO}"
      GW_RESET_GPIO: ${GW_RESET_GPIO:-17}
      DEVICE: "${DEVICE:-/dev/spidev0.0}"
      #GATEWAY_EUI_NIC: "enx00e04c68160f"
      #GATEWAY_EUI: "1122334455667788"
      TTS_REGION: "${TTS_REGION:-eu1}"
      #TC_URI: "wss://lns.example.com:8887"
      #TC_TRUST: "-----BEGIN CERTIFICATE-----MIIDJDCCAgygAwIBAgIUdoPom8rI1/IYR7dG6JyxDGSUGBQwDQYJKoZIhvcNAQELBQAwGDE...."
      #TC_CRT: "-----BEGIN CERTIFICATE-----MIICUzCCATugAwIBAgIUM3K60JYw9eRjxXly27wVD0w6QF0wDQYJKoZIhvcNAQELBQAwGDEWMBQG...."
      #TC_KEY: "NNSXS.SLOC764GN3....."
