version: "3"

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: ChirpStack Gateway
  group: LoRaWAN
  description: LoRa(WAN) gateway daemin and forwarder options
  services: 
    optional:
      - chirpstack-concentratord-slot2
      - chirpstack-gateway-relay
      - chirpstack-mqtt-forwarder
      - chirpstack-udp-forwarder
  fields:
    - name: MODEL_SLOT1
      description: Concentrator model
      default: "rak_5146"
      options: ["imst_ic880a","kerlink_ifemtocell","multitech_mtac_lora_h_868","multitech_mtac_lora_h_915","multitech_mtcap_lora_868","multitech_mtcap_lora_915","pi_supply_lora_gateway_hat","rak_2245","rak_2246","rak_2247","risinghf_rhf0m301","sandbox_lorago_port","wifx_lorix_one","dragino_pg1302","multitech_mtac_003e00","multitech_mtac_003u00","rak_2287","rak_5146","seeed_wm1302","semtech_sx1302c490gw1","semtech_sx1302c868gw1","semtech_sx1302c915gw1","semtech_sx1302css868gw1","semtech_sx1302css915gw1","semtech_sx1302css923gw1","waveshare_sx1302_lorawan_gateway_hat","multitech_mtac_lora_2g4","rak_5148","semtech_sx1280z3dsfgw1"]
    - name: INTERFACE_SLOT1
      description: Concentrator interface
      default: "SPI"
      options: ["SPI","USB"]
    - name: REGION_SLOT1
      description: Main band region
      default: "eu868"
    - name: CHANNELS_SLOT1
      description: Specific channel configuration
      default: "eu868"
    - name: RESET_GPIO_SLOT1
      advanced: True
      condition: "(INTERFACE_SLOT1 == 'SPI')"
      description: GPIO to reset the concentrator
      default: 0
    - name: MODEL_SLOT2
      condition: "('chirpstack-concentratord-slot2' in services)"
      description: Concentrator model on slot 2
      default: "rak_5146"
      options: ["imst_ic880a","kerlink_ifemtocell","multitech_mtac_lora_h_868","multitech_mtac_lora_h_915","multitech_mtcap_lora_868","multitech_mtcap_lora_915","pi_supply_lora_gateway_hat","rak_2245","rak_2246","rak_2247","risinghf_rhf0m301","sandbox_lorago_port","wifx_lorix_one","dragino_pg1302","multitech_mtac_003e00","multitech_mtac_003u00","rak_2287","rak_5146","seeed_wm1302","semtech_sx1302c490gw1","semtech_sx1302c868gw1","semtech_sx1302c915gw1","semtech_sx1302css868gw1","semtech_sx1302css915gw1","semtech_sx1302css923gw1","waveshare_sx1302_lorawan_gateway_hat","multitech_mtac_lora_2g4","rak_5148","semtech_sx1280z3dsfgw1"]
    - name: INTERFACE_SLOT2
      condition: "('chirpstack-concentratord-slot2' in services)"
      description: Concentrator interface on slot 2
      default: "SPI"
      options: ["SPI","USB"]
    - name: REGION_SLOT2
      condition: "('chirpstack-concentratord-slot2' in services)"
      description: Main band region for concentrator on slot 2
      default: "eu868"
    - name: CHANNELS_SLOT2
      condition: "('chirpstack-concentratord-slot2' in services)"
      description: Specific channel configuration for concentrator on slot 2
      default: "eu868"
    - name: RESET_GPIO_SLOT2
      advanced: True
      condition: "('chirpstack-concentratord-slot2' in services) and (INTERFACE_SLOT2 == 'SPI')"
      description: GPIO to reset the concentrator on slot 2
      default: 0
    - name: RELAY_BORDER
      advanced: True
      condition: "('chirpstack-gateway-relay' in services) and ('chirpstack-mqtt-forwarder' in services)"
      description: "Is it a border gateway?"
      options: ["true", "false"]
      default: "true"
    - name: RELAY_BORDER
      advanced: True
      condition: "('chirpstack-gateway-relay' in services) and ('chirpstack-mqtt-forwarder' not in services)"
      description: "Is it a border gateway?"
      options: ["true", "false"]
      default: "false"
    - name: RELAY_IGNORE_DIRECT
      advanced: True
      condition: "('chirpstack-gateway-relay' in services)"
      description: "Ignore direct messages?"
      options: ["true", "false"]
      default: "false"
    - name: RELAY_REGION
      advanced: True
      condition: "('chirpstack-gateway-relay' in services)"
      description: "Band to use to relay messages"
      default: "eu868"
    - name: MQTT_SERVER
      condition: "('chirpstack-mqtt-forwarder' in services)"
      description: MQTT broker to connect to
      default: "tcp://{{IP}}:1883"
    - name: UDP_SERVER_HOST
      condition: "('chirpstack-udp-forwarder' in services)"
      description: UDP packet forwarder destination host
      default: "eu1.cloud.thethings.network"
    - name: UDP_SERVER_PORT
      condition: "('chirpstack-udp-forwarder' in services)"
      description: UDP packet forwarder destination port
      default: 1700
    - name: DEVICE_SOCKET_NAME
      advanced: True
      condition: "('chirpstack-concentratord-slot2' in services)"
      default: slot1
    - name: RELAY_SOCKET_NAME
      advanced: True
      condition: "('chirpstack-gateway-relay' in services) and ('chirpstack-concentratord-slot2' not in services)"
      default: slot1
    - name: RELAY_SOCKET_NAME
      advanced: True
      condition: "('chirpstack-gateway-relay' in services) and ('chirpstack-concentratord-slot2' in services)"
      default: slot2
    - name: FORWARDER_SOCKET_NAME
      advanced: True
      condition: "('chirpstack-gateway-relay' not in services) and (('chirpstack-mqtt-forwarder' in services) or ('chirpstack-udp-forwarder' in services))"
      default: slot1
    - name: FORWARDER_SOCKET_NAME
      advanced: True
      condition: "('chirpstack-gateway-relay' in services) and (('chirpstack-mqtt-forwarder' in services) or ('chirpstack-udp-forwarder' in services))"
      default: forwarder
  post-script: |
    sleep 5 ; 
    CONTAINER=$( docker compose -p {{project}} ps -a --format "{{.ID}} {{.Name}}" | grep concentratord | awk '{print $1}' ); 
    GATEWAY_EUI=$( docker exec ${CONTAINER:-} gateway_eui ); 
    echo "Gateway EUI: ${GATEWAY_EUI:-}" 
  
# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  chirpstack-concentratord-slot1:
    image: xoseperez/chirpstack-concentratord:4
    privileged: true
    restart: unless-stopped
    volumes:
      - ipcsocket:/tmp
    environment:
      - MODEL=${MODEL_SLOT1:-RAK5146}
      - REGION=${REGION_SLOT1:-eu868}
      - CHANNELS=${CHANNELS_SLOT1:-eu868}
      - INTERFACE=${INTERFACE_SLOT1:-SPI}
      - RESET_GPIO=${RESET_GPIO_SLOT1:-17}
      - SOCKET_NAME=${DEVICE_SOCKET_NAME:-slot1}

  chirpstack-concentratord-slot2:
    image: xoseperez/chirpstack-concentratord:4
    privileged: true
    restart: unless-stopped
    volumes:
      - ipcsocket:/tmp
    environment:
      - MODEL=${MODEL_SLOT2:-RAK5146}
      - REGION=${REGION_SLOT2:-eu868}
      - CHANNELS=${CHANNELS_SLOT2:-eu868}
      - INTERFACE=${INTERFACE_SLOT2:-SPI}
      - RESET_GPIO=${RESET_GPIO_SLOT2:-17}
      - SOCKET_NAME=${RELAY_SOCKET_NAME:-slot2}

  chirpstack-gateway-relay:
    image: xoseperez/chirpstack-gateway-relay:4
    restart: unless-stopped
    depends_on:
      - chirpstack-concentratord-slot1
    volumes:
      - ipcsocket:/tmp
    environment:
      - RELAY_BORDER=${RELAY_BORDER:-false}
      - RELAY_IGNORE_DIRECT=${RELAY_IGNORE_DIRECT:-false}
      - RELAY_REGION=${RELAY_REGION:-eu868}
      - RELAY_SOCKET_DEVICES=${DEVICE_SOCKET_NAME:-slot1}
      - RELAY_SOCKET_RELAY=${RELAY_SOCKET_NAME:-slot1}
      - RELAY_SOCKET_FORWARDER=forwarder

  chirpstack-mqtt-forwarder:
    image: xoseperez/chirpstack-mqtt-forwarder:4
    restart: unless-stopped
    depends_on:
      - chirpstack-concentratord-slot1
    volumes:
      - ipcsocket:/tmp
    environment:
      - MQTT_TOPIC_PREFIX=${REGION:-eu868}
      - MQTT_SERVER=${MQTT_SERVER:-tcp://mosquitto:1883}
      - MQTT_USERNAME=""
      - MQTT_PASSWORD=""
      - MQTT_QOS=0
      #- MQTT_CA_CERT_PATH=""
      #- MQTT_CLIENT_CERT_PATH=""
      #- MQTT_CLIENT_KEY_PATH=""
      - BACKEND="concentratord"
      - BACKEND_SOCKET_NAME=${FORWARDER_SOCKET_NAME:-slot1}
      #- BACKEND_FILTER_DEVADDR=""
      #- BACKEND_FILTER_JOINEUI=""

  chirpstack-udp-forwarder:
    image: xoseperez/chirpstack-udp-forwarder:4
    restart: unless-stopped
    depends_on:
      - chirpstack-concentratord-slot1
    volumes:
      - ipcsocket:/tmp
    environment:
      - SERVER_HOST=${UDP_SERVER_HOST:-eu1.cloud.thethings.network}
      - SERVER_PORT=${UDP_SERVER_PORT:-1700}
      - SOCKET_NAME=${FORWARDER_SOCKET_NAME:-slot1}

volumes:
  ipcsocket: