version: '2'

# ---------------------------------------------------------------------------
# DCTUI CONFIGURATION
# ---------------------------------------------------------------------------

x-dctui:
  name: Portainer
  description: Docker Management WebUI
  fields:
    - name: PORT
      description: Port the service will be listening on
      default: 8000
    - name: TZ
      description: Service time zone
      default: "Europe/London"

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce:2.16.2
    ports:
      - ${PORT:-8000}:8000
      - 9443:9443
    command: --admin-password '$$2y$$05$$CamDlWaqdhRQvy1AuOZlY.4QYi/GptU6lDruXD0YiYiwQljGJmamC' --templates 'https://raw.githubusercontent.com/RAKWireless/portainer-templates/master/portainer_app_template.json'
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/London}

# ---------------------------------------------------------------------------
# PERSISTENT STORAGE
# ---------------------------------------------------------------------------

volumes:
  portainer-data:
