version: '3.4'

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: Portainer
  group: Utils
  description: Docker Management WebUI
  fields:
    - name: PORT
      advanced: True
      description: Port for the web interface
      default: 9443
    - name: TZ
      advanced: True
      description: Service time zone
      default: "Europe/London"
  success: You can now visit the Portainer web UI at https://{{IP}}:{{PORT}}, default user is `admin` and password `changeme`.

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce:2.16.2
    ports:
      - ${PORT:-9443}:9443
    command: --admin-password '$$2y$$05$$CamDlWaqdhRQvy1AuOZlY.4QYi/GptU6lDruXD0YiYiwQljGJmamC' --templates 'https://raw.githubusercontent.com/RAKWireless/portainer-templates/master/portainer_app_template.json'
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/London}

# ---------------------------------------------------------------------------
# PERSISTENT STORAGE
# ---------------------------------------------------------------------------

volumes:
  portainer-data:
