version: "3"

# ---------------------------------------------------------------------------
# ICOMPOSE CONFIGURATION
# ---------------------------------------------------------------------------

x-icompose:
  name: ChirpStack Concentratord
  group: LoRaWAN
  description: LoRa(WAN) Daemon
  fields:
    - name: MODEL
      description: Concentrator model
      default: "rak_5146"
      options: ["imst_ic880a","kerlink_ifemtocell","multitech_mtac_lora_h_868","multitech_mtac_lora_h_915","multitech_mtcap_lora_868","multitech_mtcap_lora_915","pi_supply_lora_gateway_hat","rak_2245","rak_2246","rak_2247","risinghf_rhf0m301","sandbox_lorago_port","wifx_lorix_one","dragino_pg1302","multitech_mtac_003e00","multitech_mtac_003u00","rak_2287","rak_5146","seeed_wm1302","semtech_sx1302c490gw1","semtech_sx1302c868gw1","semtech_sx1302c915gw1","semtech_sx1302css868gw1","semtech_sx1302css915gw1","semtech_sx1302css923gw1","waveshare_sx1302_lorawan_gateway_hat","multitech_mtac_lora_2g4","rak_5148","semtech_sx1280z3dsfgw1"]
    - name: INTERFACE
      description: Concentrator interface
      default: "SPI"
      options: ["SPI","USB"]
    - name: REGION
      description: Main band region
      default: "eu868"
    - name: CHANNELS
      description: Specific channel configuration
      default: "eu868"
    - name: RESET_GPIO
      advanced: True
      condition: "(INTERFACE == 'SPI')"
      description: GPIO to reset the concentrator
      default: 0
  post-script: |
    sleep 1 ; docker exec `docker compose -p {{project}} ps -a --format "{{.ID}}"` service-info
  
# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  chirpstack-concentratord:
    container_name: chirpstack-concentratord-${REGION:-eu868}
    image: xoseperez/chirpstack-concentratord
    privileged: true
    restart: unless-stopped
    volumes:
      - ipc_folder:/tmp
    environment:
      - MODEL=${MODEL:-RAK5146}
      - REGION=${REGION:-eu868}
      - CHANNELS=${CHANNELS:-eu868}
      - INTERFACE=${INTERFACE:-SPI}
      - RESET_GPIO=${RESET_GPIO:-17}

  chirpstack-gateway-bridge-concentratord:
    container_name: chirpstack-bridge-concentratord-${REGION:-eu868}
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-concentratord.toml
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - ipc_folder:/tmp
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=${REGION:-eu868}/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=${REGION:-eu868}/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=${REGION:-eu868}/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://${MQTT_BROKER:-mosquitto:1883}

volumes:
  ipc_folder: